language: php

php:
  - '7.4'

install:
  - composer install --prefer-dist --no-suggest

script:
  - composer ci
#  - composer server-fetch
#  - "./server.phar &"
#  - composer client-test

cache:
  directories:
  - "$HOME/.composer/cache/files"
